src/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

src/person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

src/vet_software/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('person.urls')),
    path('appointment/', include('appointment.urls')),
    path('animal/', include('animal.urls')),
    path('inventory/', include('inventory.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('logs/', include('audit.urls')),
    path('family/', include('family.urls')),
]

src/templates/base.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Vet Software
      {% endblock title %}
    </title>
    {% compress css %}
      <link rel="stylesheet" href="{% static 'src/output.css' %}" />
    {% endcompress %}
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <link href="https://cdn.jsdelivr.net/npm/flowbite@latest/dist/flowbite.min.css"
          rel="stylesheet" />
  </head>
  <body class="bg-gray-50 font-lato">
    <div class="h-screen w-48 fixed left-0 top-0 z-10 bg-gray-900 overflow-x-hidden pt-5">
      <li>
        <a href="{% url 'index' %}"
           class="block px-2 py-1.5 pl-8 text-2xl no-underline text-gray-500 hover:text-gray-100">Accueil</a>
      </li>
      <li>
        <a href="{% url 'calendar' %}"
           class="block px-2 py-1.5 pl-8 text-2xl no-underline text-gray-500 hover:text-gray-100">Calendrier</a>
      </li>
      <li>
        <button type="button"
                aria-controls="dropdown-client"
                data-collapse-toggle="dropdown-client"
                class="flex items-center w-full">
          <span class="block px-2 py-1.5 pl-8 text-2xl no-underline text-gray-500 hover:text-gray-100">Clients</span>
          <svg class="w-4 h-4 mr-2 text-gray-500"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               width="24"
               height="24"
               fill="none"
               viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 9-7 7-7-7" />
          </svg>
        </button>
        <ul id="dropdown-client" class="hidden py-2 space-y-2">
          <li>
            <a href="{% url 'animal_list' %}"
               class="block px-2 py-1.5 pl-8 text-xl no-underline text-gray-500 hover:text-gray-100">Animaux</a>
          </li>
          <li>
            <a href="{% url 'family_list' %}"
               class="block px-2 py-1.5 pl-8 text-xl no-underline text-gray-500 hover:text-gray-100">Familles</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="{% url 'inventory_list' %}"
           class="block px-2 py-1.5 pl-8 text-2xl no-underline text-gray-500 hover:text-gray-100">Inventaire</a>
      </li>
      <li>
        <a href="{% url 'dashboard' %}"
           class="block px-2 py-1.5 pl-8 text-2xl no-underline text-gray-500 hover:text-gray-100">Dashboard</a>
      </li>
      <li>
        <a href="{% url 'logs' %}"
           class="block px-2 py-1.5 pl-8 text-2xl no-underline text-gray-500 hover:text-gray-100">Logs</a>
      </li>
      <div class="absolute bottom-5 w-48">
        {% if user.is_authenticated %}
          <a href="{% url 'person:logout' %}"
             class="block px-2 py-1.5 pl-8 text-xl no-underline text-gray-500 hover:text-gray-100">Déconnexion</a>
          <a href="#"
             class="block px-2 py-1.5 pl-8 text-xl no-underline text-gray-500 hover:text-gray-100 mt-2.5">
            {% if request.person %}
              {{ request.person.get_full_name }}
              {% if request.person.employee.first %}
                <br>
                <span class="py-1.5 text-gray-400">{{ request.person.employee.first.role }}</span>
              {% endif %}
            {% else %}
              Admin
            {% endif %}
          </a>
        {% else %}
          <a href="{% url 'person:login' %}"
             class="block px-2 py-1.5 pl-8 text-2xl no-underline text-gray-500 hover:text-gray-100">Se connecter</a>
        {% endif %}
      </div>
    </div>
    <div class="ml-64 mr-12">
      {% block content %}
      {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/flowbite@latest/dist/flowbite.min.js"></script>
  </body>
</html>